### ISSUE TITLE
bottom bar click when container inside a form will trigger form submit

### ISSUE THREAD

**Issue by HobieCat** [box/box-content-preview#1005]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Environment:**
- Preview version: v.2.10.0, it-IT locale

**Desktop (please complete the following information):**
 - OS: GNU/Linux, macOS High Sierra
 - Browser Chrome, Firefox
 - Version Chrome 74.0.3729.169 (Official Build) (64 bit), Firefox 67.0

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Steps to reproduce the problem:**
1. Place the container div inside a form element
2. Run preview.show on that container
3. Click any bottom bar button (fullscreen, zoom in/out, etc...)

**What is the expected behavior? (Screenshots can be helpful here)**
The preview goes fullscreen

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
The form gets submitted, the preview is reloaded

**Link to application or sample code:**
https://codepen.io/anon/pen/YbdLJY
(click right arrow, start the player and click fullscreen)

**If relevant, link to file (or attach file here)**
NA

**Expected behavior**
The form does not get submitted and the preview is not reset.

**Screenshots**
NA

**Additional context**
NA

**Comment by jeremypress** [comment]
Thanks for reporting, fixed https://github.com/box/box-content-preview/pull/1007

**Comment by HobieCat** [comment]
Many thanks for the fix, may I please know when are you planning to have it available on the cdn?

**Comment by jeremypress** [comment]
Hey @HobieCat, this should be on the CDNs by end of week. I'll comment here when it's available.

**Comment by jeremypress** [comment]
Hi, version 2.11.0 with the fix is now available via our CDNs. The docs will be updated after this version completes its testing cycle.

**Comment by HobieCat** [comment]
Working great!
Ciao, grazie mille! :)
