### ISSUE TITLE
Previewing versions does not work

### ISSUE THREAD

**Issue by EmmanuelCarrara** [box/box-content-preview#1008]
**Environment:**
- Preview version: 2.10.0

**Desktop:**
 - OS: Windows 10 64bit
 - Browser: chrome
 - Version: 75

**Steps to reproduce the problem:**
1. Set the fileOptions and fileVersionId values and call the show method

**What is the expected behavior? (Screenshots can be helpful here)**
- The version of the file is previewed

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
- It always show the latest version of the file

**Example code**
var preview = new Box.Preview();
preview.show("40203550", "' + token + '", {
	container: ".preview-container",
	fileOptions: { fileVersionId: "40253574" },
	showDownload: true,
	showAnnotations: false,
	header: "light",
});

**Note**
- Both fileId and versionId were checked and are valid

**Comment by jeremypress** [comment]
Hey @EmmanuelCarrara, per the docs, the fileOptions object is a `Mapping of file ID to file-level options. See the file option table below for details`.

I think your object should look like:
```fileOptions: {
    40203550: {
        fileVersionId: "40253574"
    }
}```

Hope this helps!

**Comment by EmmanuelCarrara** [comment]
> Hey @EmmanuelCarrara, per the docs, the fileOptions object is a `Mapping of file ID to file-level options. See the file option table below for details`.
> 
> I think your object should look like:
> 
> ```
> fileOptions: {
>     40203550: {
>         fileVersionId: "40253574"
>     }
> }
> ```
> 
> Hope this helps!

It worked! Thank you very much! An example in the documentation would be appreciated. 

Another issue, the download button inside the preview downloads the latest version instead of the one you are previewing. Is that expected? Can it be implemented in the near future? Currently is confusing.

Thanks!

**Comment by jeremypress** [comment]
Good catch. I'll add to the documentation and create a separate issue for the download problem. I don't know how quickly we'll be able to fix this, but we would welcome a change if you need this fixed urgently.

**Comment by EmmanuelCarrara** [comment]
> Good catch. I'll add to the documentation and create a separate issue for the download problem. I don't know how quickly we'll be able to fix this, but we would welcome a change if you need this fixed urgently.

Thanks! We were planning to implement this next week, and we found that while testing and it was a let down. Do you think you can make the download button download the current version for the beginning of the next week?
