### ISSUE TITLE
console error when element removed before full load

### ISSUE THREAD

**Issue by bryannovoed** [box/box-content-preview#1067]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!
**Environment:**
- Preview version: 2.17

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 76

**Steps to reproduce the problem:**
1. call show and then immediately remove the dom element (this may occur when the user navigates away)

**What is the expected behavior? (Screenshots can be helpful here)**
no console error. or calling destroy or something would prevent this from happening

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
`offsetParent is not set -- cannot scroll` is shown in console

**Link to application or sample code:**
https://codepen.io/bryannovoed/pen/pozdxOp

**Comment by jstoffan** [comment]
The linked codepen is no longer available, but this should be resolved as of v2.43.0. Feel free to reopen if the issue persists.
