### ISSUE TITLE
Preview of images are compress/shrunk

### ISSUE THREAD

**Issue by azndoodle** [box/box-content-preview#1091]
I'm using Preview 2.24. 
Loading any image files (JPG, PNG, GIF, BMP) in the Previewer UI gets squashed. When I load any other type of files (so far tested PDF, WORD, EXCEL documents) they load correctly.

![previewe-issue](https://user-images.githubusercontent.com/40670270/67605937-e7805300-f74d-11e9-9142-6fb23c9c7aef.jpg)

There is nothing wrong with JPG file itself because when I download it and open it on my PC it looks just fine.

Does anyone have a fix to this?

**Comment by azndoodle** [comment]
I'm using Preview 2.24.  There is nothing wrong with JPG file itself because when I download it and open it on my PC it looks just fine.

**Comment by ConradJChan** [comment]
Hi @azndoodle, thanks for opening the issue. Are you able to reproduce the issue with a test page that loads preview of your application? I don't believe we've seen any issues with this and I'm wondering if it is possible you have some CSS in your application that may be affecting it.

**Comment by azndoodle** [comment]
global IMG css affects the previewer when displaying image files.  I removed my css on the IMG tag and it fixed the problem.
