### ISSUE TITLE
Wrong CLA Site URL in LICENSE file

### ISSUE THREAD

**Issue by salexkidd** [box/box-content-preview#1182]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

**Note:** if your issue involves annotations.js/css, please report the issue [here](https://github.com/box/box-annotations/issues/new).

**Environment:**
N/A

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Steps to reproduce the problem:**
1. Check LICENSE file in 4. Contributions

**What is the expected behavior? (Screenshots can be helpful here)**
N/A

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
N/A

**Link to application or sample code:**
https://github.com/box/box-content-preview/blob/master/LICENSE#L117

**If relevant, link to file (or attach file here)**
N/A

**Expected behavior**

**Screenshots**
Change to 
https://developer.box.com/docs/box-sdk-cla to http://opensource.box.com/cla/

**Additional context**
N/A

**Comment by salexkidd** [comment]
Hi. Any one see this issue? I think, It's a important things for committer.

Thx.

**Comment by ConradJChan** [comment]
@salexkidd, thanks for pointing this out, I'll take care of it
