### ISSUE TITLE
autofocus happens for certain files even with autofocus: false

### ISSUE THREAD

**Issue by bryannovoed** [box/box-content-preview#1213]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

**Note:** if your issue involves annotations.js/css, please report the issue [here](https://github.com/box/box-annotations/issues/new).

**Environment:**
- Preview version: 2.42.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 81

**Steps to reproduce the problem:**
1. upload file to box (pdf in this case, and only occurs for specific files)
2. embed preview container in an absolutely positioned container(autofocus: false)
3. load to page, and the preview is autoscrolled to

**What is the expected behavior? (Screenshots can be helpful here)**
no autoscrolling when autofocus: false
**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
page scrolls for the user
**Link to application or sample code:**
https://codepen.io/bryannovoed/pen/jObpJEw
**If relevant, link to file (or attach file here)**
unfortunately, the we have only been able to repro this with our customer's file. we can provide the file upon request but cannot share it publicly on this GitHub issue

**Comment by ConradJChan** [comment]
Hi @bryannovoed, thanks for opening the issue. However, as you describe above, I was also unable to repro the issue. Could you share the problematic file?

**Comment by bryannovoed** [comment]
@ConradJChan since this is a customer file that we cannot share publicly(but can share with box directly), what is the best way to share this file?

**Comment by ConradJChan** [comment]
@bryannovoed, can you provide a shared link and email it to me at conradchan@box.com?

**Comment by ConradJChan** [comment]
As discussed, this issue doesn't appear to be with the autofocus but rather PDFJS calling `scrollIntoView` when the page first renders. As of right now, there is no plan to address this
