### ISSUE TITLE
Office Viewer not working with XLSX files.

### ISSUE THREAD

**Issue by SvenSlijkoord** [box/box-content-preview#279]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

Environment:
- Preview version: Tested on 1.0.0 through 1.4.1
- Browser name and version: Chrome (59.0.3071.115), Firefox (48)
- Operating system and version:

Steps to reproduce the problem:
1. Use `preview.enableViewers('Office');` to enable the Office viewer.
2. Use the SDK to preview an XLSX file. (see sample code used)

What is the expected behavior? (Screenshots can be helpful here)
The XLSX file should be previewed in the Office viewer

What went wrong? (Screenshots can be helpful here)
![Content on the page](http://i.imgur.com/NNtR9Ft.png)
Error in console: `openExcelOnlinePreviewer?fileId=206681973542:3 GET https://cdn01.boxcdn.net/webapp_assets/integration/css/undefined 404 (Not Found)`
Error originates from the iFrame: `https://app.box.com/integrations/officeonline/openExcelOnlinePreviewer?fileId=206681973542`

Link to application or sample code:
```
preview.show(fileId, accessToken, {
              container: '.preview-container',
              header: 'none',
              logoUrl: '/static/images/icons/icon-72x72.png',
              showAnnotations: true,
              showDownload: true
            });
```

If relevant, link to file (or attach file here):
Tried with multiple XLSX files. None seemed to work.
[Monthly budget.xlsx](https://github.com/box/box-content-preview/files/1202615/Monthly.budget.xlsx)

**Comment by SvenSlijkoord** [comment]
After some more investigation, I found out that the Office preview does work when using a shared link.
Also, the 404 error on the CSS file does not seem to be related to this issue.

Maybe I am missing a scope for my access token? I am currently using the following scopes: `item_preview base_preview item_download`

**Comment by jeremypress** [comment]
Hey @SvenSlijkoord,
We're not currently supporting this viewer, but hopefully will be able to in the near future. I'll leave this open for tracking purposes.

Thanks for filing the issue!

**Comment by jeremypress** [comment]
Unfortunately there has been no progress partner wise on this issue, so I'm going to close this issue for now.
