### ISSUE TITLE
Functional tests script requires Python web server

### ISSUE THREAD

**Issue by tonyjin** [box/box-content-preview#331]
`yarn run functional-tests` doesn't work unless I start a Python web server separately. FYI @jeremypress

**Comment by jeremypress** [comment]
I have a refactor for the npm commands that fixes this coming soon.

**Comment by tonyjin** [comment]
Great! I also noticed that the functional tests may fail if you have to copy over a ton of files. #329 originally failed since I added a new directory of files to copy (for 1.7.0). I've since deleted a bunch of older directories (only keeping two most recent for any third party asset folder) and it now passes.

One other thing we'll need to keep an eye on is making sure just because we delete older versions from our source code here that the static servers still have them. There are a few older versions of pdf.js that seem to be missing (but not the oldest), but I'm not sure if that's due to the static server migration or something from this.

https://cdn01.boxcdn.net/platform/preview/third-party/doc/0.120.1/pdf.js definitely loads right now, but I'm deleting the directory as part of #329 so let's keep an eye on it.

**Comment by jeremypress** [comment]
Change here: https://github.com/box/box-content-preview/pull/334
