### ISSUE TITLE
Print option is not working.

### ISSUE THREAD

**Issue by rishiphp** [box/box-content-preview#429]
Looks like "preview.print()" method is not working.

Environment:
Preview version: 1.8.0
Browser name and version: Chrome
Operating system: Windows 10

Steps to reproduce the problem:
Load Preview
Click "Print" icon in Box header

What is the expected behavior?
Print popup has to shown.

What went wrong? (Screenshots can be helpful here)
Instead print popup, its takes me to 404 page. (Tried same with Box codepen example too, print method behaves same. )
 
![capture](https://user-images.githubusercontent.com/1487736/31329215-a53a52c8-acf6-11e7-882a-5ced0f6d3807.JPG)

**Comment by jeremypress** [comment]
Hey @rishiphp, thanks for reporting. This should be fixed as of 1.12.0, and is also fixed in our latest release 1.13.0. We'll update the codepen accordingly. Please reopen if it's still broken after upgrading.
