### ISSUE TITLE
Make FindBar Optional

### ISSUE THREAD

**Issue by georgediaz88** [box/box-content-preview#431]
Hello,
	
First off, thanks for your hard work on this JavaScript library. I wanted to know if making the find bar optional is something you'd consider? The reason for such a change is we're using this library to display a PDF that spans the height of the page rather than in a container element. In trying to achieve this, we removed the preview.css stylesheet from our code and overwrote a few styles. The last change involves disabling the "findBar" functionality since we need the scrollbar to happen along the page window and not the container element. I also noticed this library disables the browers native "search bar" which we'd be fine using if we could turn off the "findBar" functionality which disables it. So to do this, I've forked your library and made turning off the "findBar" optional -- default true. It would be used like:

`preview.show(..., { useFindBar: false })`

Here's a [link](https://github.com/georgediaz88/box-content-preview/commit/534fbdddb3f18c1a9c58a8f96b32f67617386f4f) to those code changes which I can turn into a pull request if this seems like a change you'd accept. Otherwise, let me know if there's an alternate route I can take to achieve this.

Thanks!
George

**Comment by jeremypress** [comment]
Hey @georgediaz88,
Thanks for the suggestion, we would definitely appreciate a PR for this! I think useFindBar would be better suited as a Document/Presentation viewer option, as it doesn't apply to other viewers. The config would look like this:

`preview.show({
    viewers: {
        Document: { // Or presentation
            useFindBar: false
        }
    }
});`

**Comment by georgediaz88** [comment]
@jeremypress, okay here's the pull request with the suggested changes: https://github.com/box/box-content-preview/pull/438.

Let me know if there's anything else I need to do on my end. Thanks again!

**Comment by georgediaz88** [comment]
@jeremypress, just leaving an update here that I updated the [PR](https://github.com/box/box-content-preview/pull/438) with your suggested changes.

**Comment by pramodsum** [comment]
Hey @georgediaz88, we approved your PR #438! Feel free to merge it in when you're ready 👍

**Comment by pramodsum** [comment]
@georgediaz88 merged your PR in! Thanks! It will be included in our next release v1.17.0

**Comment by georgediaz88** [comment]
Fantastic. Thanks!
