### ISSUE TITLE
Media  FullScreen but the icon is not correct

### ISSUE THREAD

**Issue by hxwhou** [box/box-content-preview#443]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

Environment:
- Preview version: 1.12.0
- Browser name and version: Chrome
- Operating system and version: Mac OS X EI

Steps to reproduce the problem:
1. Open a video to preview
2.Enter FullScreen
3.The class 'bp-enter-fullscreen-icon' should be change to 'bp-exit-fullscreen-icon'

What is the expected behavior? (Screenshots can be helpful here)
the icon should be change to 'bp-exit-fullscreen-icon'

What went wrong? (Screenshots can be helpful here)
<img width="1280" alt="qq20171019-154624 2x" src="https://user-images.githubusercontent.com/28810584/31759798-322636ba-b478-11e7-8c4c-5c10366232e9.png">Link to application or sample code:

If relevant, link to file (or attach file here):

**Comment by jeremypress** [comment]
Thanks for submitting @hxwhou, I've successfully reproduced this and we'll address it in a future release.

**Comment by jeremypress** [comment]
Fixed with #456
