### ISSUE TITLE
Option to change output view (one by each other)

### ISSUE THREAD

**Issue by igorkasyanchuk** [box/box-content-preview#463]
Environment:
- 1.17.0
- Chrome
- Windows 10

Steps to reproduce the problem:
1. Upload PPT file
2. Try to open it using BoxContentPreview.js (it works)
3. Try to make it looks like slides following each other (by scrolling)

What is the expected behavior?
Is it possible somehow to make it looks like PDF preview. I mean every slider on own slide. E.g.
[slide 1]
[slide 2]
[slide 3]
Instead of <[slide 1]>[slider 2][slide 3]

There is a possibility to do same with Viewer.js (crocodoc), but it will be deprecated soon.
Thanks

**Comment by JustinHoldstock** [comment]
Hi @igorkasyanchuk,

If you want to do this, you can set the Presentation viewer as a disabled viewer. This'll use the Document viewer for viewing PPTs.

You can use `preview.disableViewers(['Presentation'])` before `preview.show(...)` 
OR 
via the config object passed to `preview.show()` 
```javascript
preview.show(<file_id>, <auth_token>, {
  viewers: {
    Presentation: {
      disabled: true
    }
  }
});
```

As seen in our docs:
`preview.disableViewers(/* String|Array[String] */ viewers)` disables one or more viewers based on VIEWERNAME. Viewers can also be disabled by setting disabled: true on the specific viewer option inside options.

**Comment by igorkasyanchuk** [comment]
hi @JustinHoldstock , I'll try tomorrow. Thank you for 2 answers in this and another issue 🎸 👍

**Comment by aadmin** [comment]
It's great!
really works

with React, simply passed as ```props``` to ```<ContentPreview/>```

```
<ContentPreview
  fileId = { fileIds[0] }
  token = { token }
  collection = { fileIds }
  viewers = { { Presentation: { disabled: true } } }
/>
```

Thanks!
