### ISSUE TITLE
in document search

### ISSUE THREAD

**Issue by kellyrmilligan** [box/box-content-preview#466]
Is there a way to start the preview with a search already initiated? I would like to show a preview from a search result, and show the document with the search term searched in the doc when it opens.

**Comment by jeremypress** [comment]
Hi @kellyrmilligan,
We recently added a `find` method for the document viewer. You can call this after listening to the `load` event. The function can be found [here](https://github.com/box/box-content-preview/blob/master/src/lib/viewers/doc/DocBaseViewer.js#L292)

**Comment by tonyjin** [comment]
Closing as resolved
