### ISSUE TITLE
Vue + webpack

### ISSUE THREAD

**Issue by theredorm** [box/box-content-preview#492]
Halo guyz, how i can connet New Box View + Vue with yarn?
if i install box-ui-elements and import preview.js i see this.
![2017-11-16 22-45-56](https://user-images.githubusercontent.com/19307221/32912385-f7384f16-cb1f-11e7-9338-122e10e6f597.png)

**Comment by priyajeet** [comment]
@theredorm Box UI Elements use React, and not Vue.
If you want to use Preview in Vue, then you will have to use the underlying JS libraries directly.
https://developer.box.com/docs/box-content-preview
