### ISSUE TITLE
the height of container is not responsive as the height of windows?

### ISSUE THREAD

**Issue by hearttang** [box/box-content-preview#512]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

Environment:
- Preview version: v1.19.1
- Browser name and version: Chrome, FireFox.
- Operating system and version: Windows, Mac.

Steps to reproduce the problem:
1. set the value of the container height to 100% (as the attachment).
2. open the Content Preview page.
3. you can see that the height of the content preview is only 246px ![height_of_content_preview](https://user-images.githubusercontent.com/12099097/33104505-8a908016-cf63-11e7-9117-2172dc78fae9.JPG).

What is the expected behavior? (Screenshots can be helpful here)
the height of the container be responsive as the height of the windows.

What went wrong? (Screenshots can be helpful here)
the height of the content preview is only 246px
![height_of_content_preview](https://user-images.githubusercontent.com/12099097/33104505-8a908016-cf63-11e7-9117-2172dc78fae9.JPG)

Link to application or sample code:
https://github.com/hearttang/box-ui-element/blob/master/templates/contentPreview.pug

If relevant, link to file (or attach file here):

**Comment by jeremypress** [comment]
Hi @hearttang,
What's the height of the body element in this case? The preview container should be getting 100% of that height

**Comment by hearttang** [comment]
Hi @jeremypress ,
We haven't set height limit for the body.
![image](https://user-images.githubusercontent.com/12099097/33106548-884a87f2-cf6d-11e7-8dfe-5a82b374753a.png)

**Comment by jeremypress** [comment]
Since your setting the DOCTYPE to html, you'll need to pass an explicit height for the `body` and `html` elements. Check out the first answer to this SO post: https://stackoverflow.com/questions/42264049/chrome-body-and-html-height-100-by-default
