### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by jnimety** [box/box-content-preview#521]
I'd like to use just preview.js via npm/yarn  but without React. Do you have any plans to provide an npm package of just box-content-preview?

**Comment by JustinHoldstock** [comment]
Hey @jnimety,

I'm not sure that we have plans as of right now, to release Box Content Preview as its own NPM package. It's not ideal, but you could include the built scripts from our CDN (or download your own version and host) from 
https://cdn01.boxcdn.net/platform/preview/VERSION/en-US/preview.js
and
https://cdn01.boxcdn.net/platform/preview/VERSION/en-US/preview.css

Right now we're on version 1.21.0

**Comment by jnimety** [comment]
Ok, consider this a feature request. Managing a dependency like this outside of npm/yarn/etc is less than ideal. Thanks.

**Comment by keturn** [comment]
Second this. Using npm to manage our packages helps with keeping track of our dependencies, providing visibility on available updates, and works with our compilation/bundling strategy to reduce the number of requests we need to make and the number of sites we have to whitelist on our security policy.

**Comment by keturn** [comment]
I tried to download the preview.js and pull it into our bundle but that `PREVIEW_LOCATION = findScriptLocation()` trick makes it really hostile to being bundled.

**Comment by tonyjin** [comment]
Hey @jnimety & @keturn thanks for the feedback. We'll continue discussing this feature request internally.

Here are a few things we're thinking about:
- Do we want to pull React into this project for cleaner UI for some of the more advanced viewers? If so, then there's overlap we'd have to consider with the UI Elements, which are already published to npm (https://github.com/box/box-ui-elements)
- Clients shouldn't have to download the assets for all viewers (think several MB+ for 3D preview) when they only want to preview an image or document
- Internationalization gets a bit trickier if we publish this package to npm
