### ISSUE TITLE
Preview didn't load

### ISSUE THREAD

**Issue by ovvn** [box/box-content-preview#534]
I created a pen https://codepen.io/ovvn/pen/qVzvNO where it works fine.
But the same code doesn't work at https://idecisiongames.com/u/0/test-box
There're no CORS errors in chrome console. Added these to allowed origins:
![screenshot from 2017-12-08 15-50-25](https://user-images.githubusercontent.com/2973998/33766655-8e3c651c-dc2f-11e7-93cf-a936b983f622.png)

**Comment by ovvn** [comment]
Investigated the problem, looks like the error throws when loadFromServer() method is called:
Error: Cannot fetch to path: https://api.box.com/2.0/files/253887037071?fields=id%2Cpermissions%2Cshared_link%2Csha1%2Cfile_version%2Cname%2Csize%2Cextension%2Crepresentations%2Cwatermark_info%2Cauthenticated_download_url

**Comment by ovvn** [comment]
It throws the error here https://github.com/box/box-content-preview/blob/master/src/lib/Preview.js#L760 with the following url
```
fileInfoUrl = "https://api.box.com/2.0/files/253887037071?fields=id%2Cpermissions%2Cshared_link%2Csha1%2Cfile_version%2Cname%2Csize%2Cextension%2Crepresentations%2Cwatermark_info%2Cauthenticated_download_url"
```
it calls `fetch` with the following headers
```
{
  "X-Rep-Hints": "[3d][pdf][text][mp3][jpg?dimensions=1024x1024&paged=false][jpg?dimensions=2048x2048,png?dimensions=2048x2048][dash,mp4][filmstrip]",
  "Authorization": "Bearer dvBTEJVobzDVKphMCiGi0jMBeBGMzyZy",
  "X-Box-Client-Name": "box-content-preview",
  "X-Box-Client-Version": "1.21.0"
}
```
Throws with the following error
```
Error: Cannot fetch to path: https://api.box.com/2.0/files/253887037071?fields=id,permissions,shared_link,sha1,file_version,name,size,extension,representations,watermark_info,authenticated_download_url
```
Any ideas why it happens and how to fix this?

**Comment by JustinHoldstock** [comment]
@ovvn We've noticed you're using some sort of a polyfill for the fetch api that's causing some conflict 

ie) 
```
r.prototype.fetch = function() {
            return this._forSubscribable(arguments, "fetch"),
            this
        }
        ,
        r.prototype.unfetch = function() {
            return this._forSubscribable(arguments, "unfetch"),
            this
        }
        ,
        r.prototype.subscribe = function() {
            return this._forSubscribable(arguments, "subscribe"),
            this
        }
        ,
        r.prototype.unsubscribe = function() {
            return this._forSubscribable(arguments, "unsubscribe"),
            this
        }
```

Could you try using a different polyfill, or remove yours just to test, and let us know how that goes?

Thanks,
Justin

**Comment by ovvn** [comment]
@JustinHoldstock you're right, that was a problem. Thank you for your help.
