### ISSUE TITLE
Problem loading a word document with MS Office Drawing object

### ISSUE THREAD

**Issue by gabbyspg** [box/box-content-preview#543]
Environment:
- Preview version: 1.21.0
- Browser name and version: Firefox 52.2.0
- Operating system and version: Windows 7

Steps to reproduce the problem:
1. Have a document in word with a drawing object.
2. Display the document using box preview library.

What is the expected behavior? (Screenshots can be helpful here)

It should display the document. 
Here an example of the drawing object with which is not loading the Content Preview.

![ms office drawing object - word document](https://user-images.githubusercontent.com/20071063/33898381-5ae77c60-df4f-11e7-95d7-a170b8ee432b.png)

What went wrong? (Screenshots can be helpful here)

It displaying the following message

![image](https://user-images.githubusercontent.com/20071063/33899376-76011760-df52-11e7-830f-5aeed1d97187.png)

Something to mention is that document is available for download, but not displaying on preview.

**Comment by jeremypress** [comment]
Hey @gabbyspg,
Could you grant us access to the original file? It's possible that we had problems converting this document.

**Comment by gabbyspg** [comment]
Hey @jeremypress here the file.doc. Hope it helps!

[presentation issue example.zip](https://github.com/box/box-content-preview/files/1555897/presentation.issue.example.zip)

**Comment by jeremypress** [comment]
Unfortunately we're having a problem converting that file. A workaround would be to save that drawing object as an image and including it in the word document instead.
