### ISSUE TITLE
Presentation with audio

### ISSUE THREAD

**Issue by gabbyspg** [box/box-content-preview#544]
Environment:
- Preview version: 1.21.0
- Browser name and version: Firefox 52.2.0
- Operating system and version: Windows 7

Steps to reproduce the problem:
1. Load a presentation with audio using box preview library.

What is the expected behavior? (Screenshots can be helpful here)

Load audio for presentation.

![image](https://user-images.githubusercontent.com/20071063/33899794-bc91bce2-df53-11e7-85b0-4bd2d6c6c7c0.png)

What went wrong? (Screenshots can be helpful here)

Just displaying the presentation. Is there a way to reproduce the audio on content preview? or those are not supported files?

**Comment by jeremypress** [comment]
Hi @gabbyspg,
Unfortunately we don't currently support preview for audio or video within powerpoint files.
