### ISSUE TITLE
Pinching to zoom on mobile is buggy

### ISSUE THREAD

**Issue by ascot21** [box/box-content-preview#551]
On mobile (iOS), zooming by pinching with your fingers is not smooth at all.  The preview zooms but it happens in a very jerky motion.  This happens in my app as well at the official demo (https://codepen.io/box-platform/pen/rmZdjm).

This wasn't happening in the old Crocodoc viewer but we recently migrated to this new one and noticed it.

**Comment by jeremypress** [comment]
Hey @ascot21,
Thanks for bringing this up. Unfortunately this is a result of our change in preview technology. Now on zoom we are re-rendering the document, as opposed to just scaling the Crocodoc image assets. While this gives us greater rendering flexibility, zooming speed is a drawback. We will revisit this issue to see if we can take a hybrid approach of scaling the canvas initially, and then applying the re-rendered zoom after the user has finished pinching.

**Comment by ascot21** [comment]
@jeremypress Thanks for the quick response. Our use case is primarily mobile and frankly the way it works now is almost unusable.

**Comment by ascot21** [comment]
@jeremypress my management is really pushing this issue as it makes moving over to the new API not possible for us by the Jan 15th deadline.  Can we escalate this and get a fix for this soon?

**Comment by ascot21** [comment]
Ok, thanks for the help.  Let me know if you want/need me to help test anything.

**Comment by jeremypress** [comment]
Here's some more context on the issue, we're planning on taking a look today. https://github.com/mozilla/pdf.js/issues/2582

**Comment by ascot21** [comment]
Did you have any luck with solving this?

**Comment by jeremypress** [comment]
He @ascot21, here's my initial solution. Please play around with it and let me know what you think!

**Comment by ascot21** [comment]
@jeremypress I just finished playing around with it and it's definitely a vast improvement.  I did notice the small issues you mentioned in the PR but I we can live with those for now.  Thanks for the work and let us know when you can release a new build with this in it.

**Comment by jeremypress** [comment]
This is now merged and will be a part of our next release (1.26) that is targeted for Tuesday. We will continue to work on improvements/performance, please submit additional issues if needed. I'll close this when the release is out.

**Comment by ascot21** [comment]
@jeremypress Thanks for your work on this!
