### ISSUE TITLE
Support for GetVersions

### ISSUE THREAD

**Issue by a1626** [box/box-content-preview#570]
Is there any way to use [getVersions](https://developer.box.com/v2.0/reference#view-versions-of-a-file) API, that user can switch between versions of a particular file?

**Comment by tonyjin** [comment]
Thanks for the request - we're planning on implementing this before the end of the month.

**Comment by a1626** [comment]
Thank you for the update. I have a follow up question. We are evaluating to integrate box viewer. Is there a plan to support viewing of different versions of a file within the box viewer. 
For example, given a file id and version id to preview js , would it load a particular version of the file.
