### ISSUE TITLE
[question] Is there a limit for content preview?

### ISSUE THREAD

**Issue by ovvn** [box/box-content-preview#571]
For example, what happens if 100 users will simultaneously preview a content in 1 second?

**Comment by jeremypress** [comment]
Hey @ovvn, Preview relies on the Box Content API and is subject to the same [rate limiting restrictions](https://developer.box.com/v2.0/reference#rate-limiting). 

`There are two limits. The first is a limit of 10 API calls per second per user. The second limit is 4 uploads per second per user.`

**Comment by ovvn** [comment]
Hi @jeremypress, does it mean that 10 previews in a second is a limit? How many api calls does a single preview do? Is there a way to workaround the rate limits?

**Comment by jeremypress** [comment]
Each preview makes the following API calls; one call to fetch the [representations](https://developer.box.com/v2.0/reference#get-representations) for a file, and then the subsequent calls needed to [fetch the contents](https://developer.box.com/v2.0/reference#fetching-a-pdf-representation) of that file (varies depending on file size). As mentioned before this is on a per user basis. So in your example each of your 100 users would be able to make 10 requests in a second. It doesn't matter if they are all previewing at the same time, only that each user his/herself does not surpass the limit. 

There's no way to work around these restrictions, but Preview will detect a rate limit error and send display the appropriate message on the client.

**Comment by ovvn** [comment]
Thanks for the information. I'm thinking about a relation between actual number of users and "box users". Preview is called as follows: 
```coffeescript
    @preview.show fileId, accessToken,
      container: previewContainer
```
So if 100 users open up a preview with the same `accessToken` wouldn't it mean that actually only one box user opens up a preview 100 times?

**Comment by ovvn** [comment]
@jeremypress can you please answer the question above?

**Comment by jeremypress** [comment]
Yes, however depending on your authentication strategy you can avoid this. If your users are already box users, then you can authenticate with oAuth2 and make API calls on their behalf. This would mean that each user makes API calls with unique tokens.
https://developer.box.com/v2.0/reference#user-object

If your users are not box users, you can implement "[App Users](https://developer.box.com/docs/app-users)" to accomplish the same scale but without being tied to box accounts. 

What's your intended use case for your application? How are you planning on authenticating?

**Comment by ovvn** [comment]
@jeremypress thank you for the answer. I have a business plan with "OAuth 2.0 with JWT (Server Authentication)" application. On the server side of my node project I obtain an access token as follows:
```coffeescript
  getAccessToken: (req, res) ->
    enterpriseClient = sdk.getAppAuthClient 'enterprise', enterpriseID
    enterpriseClient._session.getAccessToken()
      .then (token) ->
        res.json {token}
```
The access token is used for generating preview. Should I create a new app user each time I need to generate a unique access token?

**Comment by jeremypress** [comment]
@mattwiller's response to your issue in the node SDK applies here as well. If you're still unclear on your strategy for authentication I would file a support ticket with Box, as this repo is geared to using the preview library and not really with authentication.

Hope this helps!

**Comment by ovvn** [comment]
Thanks!
