### ISSUE TITLE
Is there a way to change the base request url?

### ISSUE THREAD

**Issue by tatums** [box/box-content-preview#592]
Is there a way to change the base url? 

For example, instead of `https://api.box.com` can I configure box-content-preview to make its requests to `https://[MY-DOMAIN]/api/box` ?  

Let me explain my use case.  We have a multi-tenant app. We allow tenants to bring their own domain. We've automated many of the setup steps, but one of the remaining steps is to login to the Box dev console and add the domain for CORS (AFAICT there isn't a way to programmatically update this list). The list is fairly long list and the process is error prone. 

If I could route box-content-preview requests to my backend and proxy to `https://api.box.com/2.0/` CORS would no longer be in play.

**Comment by pramodsum** [comment]
Hi @tatums! 
You can pass in a custom apiHost to the preview options which will then be used for [API requests from Preview](https://github.com/box/box-content-preview/blob/master/src/lib/file.js#L29). That particular option is not currently documented. 

The custom apiHost is read in here: https://github.com/box/box-content-preview/blob/master/src/lib/Preview.js#L726

We do plan on fixing the CORS issue later this year.

**Comment by tatums** [comment]
@pramodsum Excellent! Thank you!

**Comment by itamarzil123** [comment]
I use a reverse proxy as well and instead of api.box.com I use mydomain.com (change constants like API_HOST to my custom domain). However, there is still a request to dl.boxcloud which I couldn't find in the code and don't know how to change it to my domain. (organizations that block boxcloud.com cannot view files therefore)
