### ISSUE TITLE
hosting the SDK

### ISSUE THREAD

**Issue by keturn** [box/box-content-preview#595]
[reposting from https://community.box.com/t5/Box-Developer-Forum/hosting-the-Content-Preview-SDK/m-p/49805 at the request of the moderator there]

The documentation at https://developer.box.com/docs/box-content-preview says

> You can self-host the Preview UI Element or reference the versions hosted on the Box CDN.

but when I tried to use a copy I had saved locally, it failed on `findScriptLocation`. Apparently it depends on its name being hard-coded? And in the comment where it calls findScriptLocation, it refers to using that as a base for "all preview assets."

Does that mean there are other assets I'd have to host as well, in addition to the two files preview.js and .css?

Using our hosts would avoid adding exceptions to our security policy.

**Comment by pramodsum** [comment]
Hi @keturn! 
You shouldn't need any other assets other the preview.js and preview.css file. However, the path structure needs to be structured as such, `/{version}/{locale}/preview.js` i.e. https://cdn01.boxcdn.net/platform/preview/1.26.0/en-US/preview.js

**Comment by pramodsum** [comment]
One correction! You will actually need to host the entire `/dist` folder which is created after compiling preview. 

To determine which preview/third party assets you need to self-host:
1. Check out the latest version of Preview ([v1.26.0](https://github.com/box/box-content-preview/releases/tag/v1.26.0))
2. `yarn install && yarn run prod`
3. Everything in the `/dist` folder needs to be hosted yourself

**Comment by hunterbrowning** [comment]
@pramodsum Tagging on here, 

Following your instructions I get an error from Yarn with an exit code of it not being able to find:

"/box-content-preview/src/i18n/json/en-AU.json"

as there is no `json` folder in the `i18n` when I clone the repo at v1.26.0 or v1.28.0

Any steps I am missing to accomplish your solution described here besides cloning, installing dependencies and running the yarn command as you guys have listed?

**Comment by jeremypress** [comment]
Hey @hunterbrowning,
as a workaround, try running `yarn build-rb` before running `yarn prod`. This will generate the i18n files beforehand. We should have a fix for the script up soon.

**Comment by hunterbrowning** [comment]
@jeremypress That did the trick for me. Thanks for the prompt response.
