### ISSUE TITLE
Load event listener error

### ISSUE THREAD

**Issue by NoelOConnell** [box/box-content-preview#603]
Hi,

Some of our users are getting an error from the load event listener about 10 times a day each.
These files are either pdfs or word files.

Environment:
- Preview version: 1.24.0
- Browser name and version: Chrome 63
- Operating system and version: Windows 10

I added logging to the error result to see what the issue is but it's seems generic.
I looked through the code and the `error_refresh` message is shown after the file failed to load.

It looks like that message appears after a failed fetch from the `loadFromServer` function.
Is there any reason why files would failed to load so many times a day?
Or any pointers to look at to track down the issue?

Below is the output from the load event listener.

Thanks

```json
{
  "error": "We're sorry, the preview didn't load. Please refresh the page.",
  "metrics": {
    "locale": "box-viewer",
    "event": "preview",
    "browser": {
      "name": "Chrome",
      "swf": false,
      "svg": true,
      "mse": true,
      "webgl": true,
      "mp3": true,
      "dash": true,
      "box3d": true,
      "h264": {
        "baseline": true,
        "main": true,
        "high": true
      }
    },
    "client": {
      "name": "box-content-preview",
      "version": "1.24.0"
    },
    "converted": true,
    "cache": {
      "hit": false,
      "stale": false
    },
    "time": {
      "conversion": 0,
      "rendering": 220,
      "total": 220
    },
    "count": {
      "success": 1,
      "error": 2,
      "navigation": 0
    }
  },
  "file": {
    "id": "269035XXXXX"
  }
}
```

**Comment by JustinHoldstock** [comment]
Hey @NoelOConnell,

Would you be able to provide us with the status of the network request(s) that fail to load, if any exist?

Thank you!

**Comment by NoelOConnell** [comment]
@JustinHoldstock 

It can't replicate it on my own environment. It's being reported to us from multiple clients in different countries.

So I don't have the network request info. Is there a way to enable more detailed logging or should I just customise the viewer to log that info?

Here's a sample of our logs yesterday. You can see it happens on IE and Chrome and for different users.

![image](https://user-images.githubusercontent.com/966495/35431973-794916ec-0276-11e8-972d-78107535cdc0.png)

**Comment by JustinHoldstock** [comment]
Hey @NoelOConnell,

We suspect there may be issues with converting that file. Have you tried viewing the exact files that are causing the issue? (Not copies that you've uploaded)

Does the issue happen consistently, or can the files be successfully viewed some times?

Would you be able to provide the full FileIDs of several of the offending files? You can email them to jholdstock@box.com :)

Thanks,
Justin

**Comment by NoelOConnell** [comment]
Thanks @JustinHoldstock 

The files load fine on my PC when I go to view them so I think that rules out any converting issue.
The client said it can be resolved for a short period of time by clearing their cache/cookies but I can not confirm that solves the issue.

It feels like a network issue.
Since it throws the `error_refresh` message, I will add some more logging to the viewer were this error is called and try and get more details.

**Comment by JustinHoldstock** [comment]
Hey @NoelOConnell,

Any advancements on this? 

Thanks!
Justin

**Comment by NoelOConnell** [comment]
@JustinHoldstock Apologies for the delayed reply.

We changed the viewer to proxy all the requests through our server. It's seem like this is working so far. We're still monitoring it. Our guess was that the requests to box.com were not allowed on some companies network.

It might be helpful for others if the network request errors were thrown with the response info.
Currently it returns the `error_refresh` message.

Thanks

**Comment by JustinHoldstock** [comment]
@NoelOConnell No worries at all!

Glad to hear everything is working now :) You can now listen to your preview instance for `preview_error` events. The event will contain an `error` which holds `details`, `message`, and a `code` to help you debug any issues. See `PreviewError.js`, and `emitPreviewError()` inside of `Preview.js` for more.

ie) 
```
preview.on('preview_error', (errEvent) => {
  if (errEvent.error.code === 'bad_things') {
    console.log(':[');
  }
});
