### ISSUE TITLE
DocFindBar close triggers error

### ISSUE THREAD

**Issue by hunterbrowning** [box/box-content-preview#614]
Environment:
- Preview version: 1.28.0
- Browser name and version: Chrome - 63.0.3239.132
- Operating system and version: MacOS 10.11.6

Steps to reproduce the problem:
1. `cmd + f` to get the find box
2. Type in search.
3. Clicking the "close" x

What is the expected behavior? (Screenshots can be helpful here)

What went wrong? (Screenshots can be helpful here)
 Clicking the close x triggers a error in console "Cannot read property 'value' of undefined". The find box then does not go away. 

Arrows and finding the search term is working properly. Only issue with the close button. I first started interacting with this at v1.24.0 and have seen this problem since then. 

I am using the CDN browser link so don't know this for sure but I am guessing the error is thrown at line 389 of src/lib/viewers/doc/DocFindBar.js if thats any help. 

![image](https://user-images.githubusercontent.com/3359009/35606883-08807744-0617-11e8-95c3-e0a3478b08ab.png)

**Comment by jeremypress** [comment]
Thanks for reporting @hunterbrowning. Will be fixed by this [commit](https://github.com/box/box-content-preview/pull/615)
