### ISSUE TITLE
publish API documentation

### ISSUE THREAD

**Issue by keturn** [box/box-content-preview#641]
When I went digging a little to find out how I might update a token, I found that there's already a method to do this, complete with documented parameters and types. But that wasn't on https://developer.box.com/docs/box-content-preview or in the `preview.js` you direct people to load (since that's minified), it was only because I was stumbling around in the GitHub sources that I saw it.

Please make this API documentation (that you've already written!) more discoverable from the Box Developers site. Thanks!

**Comment by tonyjin** [comment]
Thanks for the report, we haven't publicly documented this feature since 1) we weren't sure if anyone was interested in this functionality outside of our internal use cases and 2) we may want to change the interface.

Thanks for confirming there is a use case—we'll consider what interface we want to settle on and document it.

**Comment by mobpakrd** [comment]
@tonyjin we've also run into this issue of expiring tokens. Should we hold off on attempting to implement it if the interface is likely to change?

**Comment by mobpakrd** [comment]
Also what would be a timeline we could expect this to be finalized?

**Comment by freyley** [comment]
@tonyjin Any news on this?

**Comment by freyley** [comment]
@tonyjin Ping? Is this happening still?

**Comment by tonyjin** [comment]
@freyley @mobpakrd apologies I think I accidentally have these notifications filtered. We decided to keep the interface for box-content-preview and make modifications to the interface at a higher level in box-ui-elements.

#807 adds documentation for the token generator function here. Please let me know if you have any questions.
