### ISSUE TITLE
cdn links don't work

### ISSUE THREAD

**Issue by ovvn** [box/box-content-preview#670]
https://cdn01.boxcdn.net/platform/preview/1.31.0/en-US/preview.css and https://cdn01.boxcdn.net/platform/preview/1.31.0/en-US/preview.js return 404

**Comment by JustinHoldstock** [comment]
@ovvn,

I apologize for that. I made a mistake when doing a patch release, last week.
The links have been updated in the README, to reflect 1.30.1

Thank you for catching this!

Cheers,
Justin
