### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by ovvn** [box/box-content-preview#678]
Preview doesn't work showing the error
<img width="774" alt="materials_instructions1" src="https://user-images.githubusercontent.com/2973998/36530529-5a405de4-17cc-11e8-9bd2-c48481d3fe2e.png">

Using the assets https://cdn01.boxcdn.net/platform/preview/1.30.0/en-US/preview.css and https://cdn01.boxcdn.net/platform/preview/1.30.0/en-US/preview.js

**Comment by ovvn** [comment]
Rolling back to 1.29.0 fixed the preview.

**Comment by jeremypress** [comment]
Hi @ovvn,
This was fixed in 1.30.1 going forward. Thanks for reporting. 
https://github.com/box/box-content-preview/releases
