### ISSUE TITLE
Can we use this  library for rendering files NOT stored on Box ?

### ISSUE THREAD

**Issue by meteorplus** [box/box-content-preview#684]
Hello guys,
great work but Can we use this  library for rendering files NOT stored on Box ?

I have some base64 files and would love to use this awesome library to render my files...

Thank you

**Comment by DanDeMicco** [comment]
Hi @meteorplus unfortunately no, box-content-preview is specifically for previewing content which is stored on Box. Consider using [Box Platform](https://www.box.com/platform) so you can leverage our awesome preview library 👍
