### ISSUE TITLE
Disable/enable hot keys doesn't work

### ISSUE THREAD

**Issue by AnatoliiSirosh** [box/box-content-preview#723]
Environment:
- Preview version: 1.33.0, 1.33.1, 1.34.0
- Browser name and version: Chrome 65.0.3325.162, Firefox 59.0.1, EDGE 38.14393.2068.0
- Operating system and version: Windows 10

Steps to reproduce the problem:
1. Open file preview
2. Press CTRL + F

Expected behavior: When I call `preview.disableHotkeys();`, search in document shouldn't work.

Actual behavior: Search works.

[CodePen](https://codepen.io/anon/pen/zWKKYV)

**Comment by DanDeMicco** [comment]
Hey @AnatoliiSirosh thanks for the report! It looks like this particular event got missed out on being disabled. I should be able to look into the issue this week and will keep you updated.

**Comment by AnatoliiSirosh** [comment]
@DanDeMicco Thank you!
