### ISSUE TITLE
We're sorry, the preview didn't load error

### ISSUE THREAD

**Issue by addula** [box/box-content-preview#760]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

Environment:
- Preview version: 1.35.0
- Browser name and version: Chrome latest
- Operating system and version: MacOS High Sierra

Steps to reproduce the problem:
1. Load preview.js and css with the cdn provided from box documentation
2. Try preview.show() with access token and fileId
3. We're sorry, the preview didn't load comes with download button

What is the expected behavior? (Screenshots can be helpful here)
Page should be loaded with the file

What went wrong? (Screenshots can be helpful here)
![image](https://user-images.githubusercontent.com/8180863/38405079-a638c318-398b-11e8-9684-eeec81efee50.png)

Link to application or sample code:
var ACCESS_TOKEN = 'valid_access_token';
                        var FILE_ID = 'valid_file_id';
                        var preview = new Box.Preview();
                        preview.show(FILE_ID, ACCESS_TOKEN, {
                            container: '.preview-container',
                            showDownload: true
                        });

If relevant, link to file (or attach file here):

**Comment by stariqmi** [comment]
Experiencing the same issue - this seems like a regression since it was working for me in `v1.33.0`.

**Comment by stariqmi** [comment]
Updating to `v1.37.0` seems to fix it.

**Comment by jeremypress** [comment]
@stariqmi glad that's fixed. @addula, can you try upgrading? If that doesn't help, what kind of network or console errors are you seeing when Preview fails?
