### ISSUE TITLE
annotations.css contains not prefixed rules

### ISSUE THREAD

**Issue by vladyslav-nadtoka** [box/box-content-preview#761]
Environment:
- Preview version: tested with 1.34.0 and 1.38.1 (probably same situation for lower versions)
- Browser name and version: any
- Operating system and version: Windows 10

Steps to reproduce the problem:
1. Show file preview with enabled annotations

What is the expected behavior:
Сss styles of the box previewer does not affect outer application; 
All styles related to the box previewer modify only the box previewer inner markup;

What is the current behavior:
annotations.css (namely box-react-ui/lib/styles/common/forms.scss) contains rules that modify inputs style by tag + attr. 
These rules have impact on styles of application that consumes box previewer.
Example:` input[type="text"], input[type="password"]` etc.

**Comment by jeremypress** [comment]
Thanks for reporting @vladyslav-nadtoka, we'll take a look.

**Comment by jeremypress** [comment]
Here's the PR to prefix the rules: https://github.com/box/box-annotations/pull/165

**Comment by gblachonupg** [comment]
Thank you for that, we really need that too.

Regards,

**Comment by jeremypress** [comment]
hi @vladyslav-nadtoka  and @gblachonupg, this should be fixed in preview 1.40.0

**Comment by vladyslav-nadtoka** [comment]
@jeremypress thanks a lot! Great job.
