### ISSUE TITLE
[Question] Multiple api calls for one file

### ISSUE THREAD

**Issue by gjdownes** [box/box-content-preview#787]
Environment:
- Preview version: 1.40.0
- Browser name and version: Chrome 65.0.3325.181
- Operating system and version: Windows 10

Steps to reproduce the problem:
1. Upload a PDF to Box
2. Generate Access Token and initialize content preview with File Id and token
3. Load the content preview and observe dev tools

What is the expected behavior? (Screenshots can be helpful here)
I'm not sure.

Multiple API calls seem to be made for one document. Based on my rough analysis, it appears the file is being downloaded in chunks by the viewer. 

![image](https://user-images.githubusercontent.com/103374/39402330-428cc6a6-4b2a-11e8-884d-8a18f3a63fe6.png)

I'm just concerned the # of calls is counting towards my API quota (Platform plan). Just wondering if this is expected behavior and if there are possibilities to optimize if the calls do in fact count towards quota (will contact support for confirmation).

**Comment by JustinHoldstock** [comment]
Hey @gjdownes,

It appears that, after talking to Customer Success, you've submitted a ticket asking about this. I've brought this to their attention and they've said they'll get back to you if they haven't already.

Thanks!
Justin
