### ISSUE TITLE
[Bug] The preview of files stored on a device does not work

### ISSUE THREAD

**Issue by stas-dolgachov** [box/box-content-preview#793]
**Environment:**
- Preview version: 1.42.0

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad
 - OS: iOS 10+
 - Browser: Hybrid applications using Cordova
 - Version: Cordova 6.5.0, Cordova-ios v.4.5.4

**Steps to reproduce the problem:**
1. Save a representation of a file to the device with all Box required metadata.
2. Try to preview this file using passed well-formed Box metadata.

**What is the expected behavior? (Screenshots can be helpful here)**
A file is previewed using the well-formed Box metadata (without calls to back-end for a file representation or related metadata)

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
Preview tries to get a file metadata from the Box server and file is not displayed.

**Link to application or sample code:**
```
  const preview = new Box.Preview();
  const boxFile = { ...the object which contains all required Box file data... };
  preview.show(boxFile, '', {
       skipServerUpdate: true,
       container: '.preview-container',
       header: 'none'
   });
```
**We intentionally do not provide token, because we want to preview a file stored on the device**

**Expected behavior**
We are expecting to have an ability to preview files stored on the device. This functionality was introduced in the [https://github.com/box/box-content-preview/pull/326](https://github.com/box/box-content-preview/pull/326)
And was available in the Preview v. 1.22.0

Thank you in advance!

**Comment by DanDeMicco** [comment]
Hi @stas-dolgachov thanks for the bug report. I will add this to our backlog, but it might take some time for us to get around to taking a look and fixing this. We would welcome the help to bisect the issue, and/or submitting a pull request for the fix!

**Comment by stas-dolgachov** [comment]
Hi, @DanDeMicco thanks for your response. I created a pull request with the fix. Could you or someone from contributors take a look at it? https://github.com/box/box-content-preview/pull/799
Thank you in advance.

**Comment by pramodsum** [comment]
Thanks for submitting this PR @stas-dolgachov. We have merged in your change and it will be included in our next Preview release!
