### ISSUE TITLE
I want an API to get the user's metrics

### ISSUE THREAD

**Issue by hxwhou** [box/box-content-preview#805]
**Describe the solution you'd like**
If the user played a video through box preview, I want to know how much of the video did they play?  (either the time the stopped or the % of the video or both!!)

**Describe alternatives you've considered**
I want an API to get the metrics info about how much of the video did user preview.

**Additional context**
If you're already a Box customer, please send an email preview-team@box.com with your admin's information/enterprise ID.

**Comment by jeremypress** [comment]
hi @hxwhou, this is something that we don't currently track internally, but could be calculated by you on the client. You could start counting on the play event and stop counting on the pause/stop event or when the viewer is destroyed. You can also get the total time of the video from the video element itself `videoEl.duration`.
