### ISSUE TITLE
How to disable auto scroll when preview file loading gets completed

### ISSUE THREAD

**Issue by ganny26** [box/box-content-preview#960]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Note:** if your issue includes a potential security vulnerability, please do not file it here. Instead, email the issue to security@box.com for support.

**Note:** if your issue involves annotations.js/css, please report the issue [here](https://github.com/box/box-annotations/issues/new).

**Environment:**
- Preview version:

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome,Mozilla,Safari
 - Version 74,6

**Steps to reproduce the problem:**
1. Lets say i have a page where box preview placed at bottom of the page
2. When box preview file completes loading the file automatically parent page scrolling to bottom
3. Check this codepen for example https://codepen.io/ganny26/pen/rRdeNy

**What is the expected behavior? (Screenshots can be helpful here)**
When box preview is loaded why parent view is scrolled automatically it is annoying since user may be reading something from the top when box preview gets loaded unnecessarily focusing to preview view, because of this user need to scroll again to top to view the content

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
Enable a config to control box preview need to be focused or not

**Link to application or sample code:**
https://codepen.io/ganny26/pen/rRdeNy

**If relevant, link to file (or attach file here)**

**Expected behavior**
Enable a config to control box preview need to be focused or not. Don't wont to scroll automatically by default

**Screenshots**
Check below video
https://youtu.be/0ftkZOO9Nhk

**Additional context**

**Comment by ConradJChan** [comment]
Hi @ganny26, thanks for opening the issue. Have you tried the `autoFocus: false` option?

**Comment by ganny26** [comment]
Hi @ConradJChan Thank you for the reply. if I'm using from preview weboption script `autoFocus` helps, but currently i'm using [Box Embed](https://developer.box.com/docs/box-embed) link with iframe in that case how to configure `autoFocus` param?

**Comment by ConradJChan** [comment]
Unfortunately, that's not within the control of the Preview SDK. If you would like you could submit your feedback here: https://pulse.box.com/forums/909778-feedback?category_id=338329
