### ISSUE TITLE
Full screen mode doesn't work on mobile browsers

### ISSUE THREAD

**Issue by Band-Aid** [box/box-content-preview#966]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Environment:**
- Preview version: 2.4.0

**Smartphone (please complete the following information):**
 - Device: all iphone, ipad
 - OS: ios 12
 - Browser safari, chrome

**Steps to reproduce the problem:**
1. Open preview element 
2. press the full screen icon
3. nothing happens
![image](https://user-images.githubusercontent.com/21311546/55055805-81dcc300-50a7-11e9-97c4-860790676c97.png)

**What is the expected behavior? (Screenshots can be helpful here)**
Should display preview in full screen mode

**Link to application or sample code:**
https://codepen.io/box-platform/pen/rmZdjm
This is reproducible not just with the ui elements. Can reproduce with any box preview
https://dbox.box.com/s/m558aulwme37048sj9u3e0luh4xffga3

Possible Related issue #836

**Comment by jstoffan** [comment]
Hi @Band-Aid. The fullscreen button on mobile only removes the Preview header to provide slightly more vertical space for the document. Limitations of the iOS platform preclude true fullscreen support.

We may consider removing the button entirely on mobile in the future to avoid this confusion.

**Comment by Band-Aid** [comment]
I just found `Fullscreen api` with in iPad's safari experimental features.(and it works!)
In hopes apple will make this an official feature in the future, can we keep the button? 

![image](https://user-images.githubusercontent.com/21311546/55208675-66e28e00-5222-11e9-8028-567d7e2178a2.png)

**Comment by jstoffan** [comment]
That's interesting; thanks for sharing. We'll definitely keep that in mind as we move forward. Since this behavior is caused by an intentional setting in iOS Safari, I'm going to mark the issue as Closed. Let us know if you have any additional thoughts or questions.
