### ISSUE TITLE
Can I use custom api host and custom dl host for rendering a preview?

### ISSUE THREAD

**Issue by sdole** [box/box-content-preview#983]
Hello,

I would like to download box documents on my own server using a box service account and use the new self hosted document URL as the document URL in the previewer?

Is that possible to do? I have a solid reason for doing so and can share if required.

Best,
Sachin Dole

**Comment by ConradJChan** [comment]
Hi @sdole! 

Unfortunately, I don't think that is possible. Preview relies on the public Box APIs (https://developer.box.com/reference) to fetch file information as well as the content so picking and choosing which URL to use won't work. However, if you proxy all the APIs through your own server, that might be another solution which other customers have looked into.
